### ISSUE TITLE
404 page picture

### ISSUE THREAD

**Issue by JeffCousineau** [WalkingMachine/walkingmachine.github.io#23]
Picture is way to heavy, it's almost 10mo, causing a slow loading.
You can resize it by at least half the size and compress it until you have no more than 2mo.

**Comment by gregoirefra** [comment]
Issue #16 would also help since the page would load without content and the rest would load depending on the 2nd server connection. It will also be usefull for #14 since it will load any media after/in parallel to the rest of the page

**Comment by JeffCousineau** [comment]
Ouais ben toutes nos photos on peut les mettre sur globo ! C'est moins chiant aussi par après si pour une raison ou une autre faut cloner le repo, t'as pas 200mo de photo a download :P
