### ISSUE TITLE
Firefox bug d'affichage

### ISSUE THREAD

**Issue by gortium** [WalkingMachine/walkingmachine.github.io#48]
@TheDaringDan commented on [Fri Nov 18 2016](https://github.com/WalkingMachine/sara_commun/issues/73)

![firefox](https://cloud.githubusercontent.com/assets/6043152/20441053/be9b7942-ad90-11e6-9575-1c40df3205bb.png)

Il semble avoir une case vide qui apparaît quand il y a un sous-titre donné a un membre. 

---

@JeffCousineau commented on [Fri Nov 18 2016](https://github.com/WalkingMachine/sara_commun/issues/73#issuecomment-261608658)

To reproduce the same error :
1. Open firefox in linux
2. Open the menu and click on devopper tab
3. Click on "responsive design mode"
4. Select "1920x900" preset

---

@gortium commented on [Wed Nov 30 2016](https://github.com/WalkingMachine/sara_commun/issues/73#issuecomment-263916303)

Cette issue ne devrait pas etre ici. Elle devrait etre dans le repo du site.

**Comment by TheDaringDan** [comment]
Bon, j'ai trouvé le problème. Dans le _layouts/team.html , seulement un des paragraphes contient une balise `<p>` avec un paramètre `style="height:35px"`. Il faut juste rajouter ce tag dans la balise `<p>` du sous-titre de membres, qui, en ce moment, dépasse de 0.2 pixels selon Firefox...

https://walkingmachine.slack.com/files/daringdan/F39JXH4EM/screenshot_from_2016-12-03_16_30_37.png
