### ISSUE TITLE
Add a custom 404 page

### ISSUE THREAD

**Issue by JeffCousineau** [WalkingMachine/walkingmachine.github.io#7]
Refer to this : https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by gregoirefra** [comment]
@JeffCousineau est-ce que tu pourrais nous avoir une photo de la face de sara qui est triste. C'a fiterais bien je trouve avec un 404 not found comme un peu le robot de google sur des pages qui fonctionne pas

**Comment by JeffCousineau** [comment]
Jte fais ça live !

**Comment by gregoirefra** [comment]
Merci :)

**Comment by gregoirefra** [comment]
Quand tu l'aura simplement la commit dans feature_404
